name: Build Go

on:
  workflow_dispatch: null
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.

  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-go@7a3fe6cf4cb3a834922a1244abfce67bcef6a0c5 # v6.2.0
        with:
          go-version: 'stable'
      - name: Build
        run: go build -v ./src/Go/NewtonRaphthonMethod
