name: Build Dotnet

on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: 0 0 * * 0 # At 00:00 on Sunday.
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-24.04, windows-2025, macos-26]
    permissions:
      contents: read
    runs-on: ${{ matrix.os }}
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1
        with:
          persist-credentials: false
      - uses: guitarrapc/actions/.github/actions/setup-dotnet@main
      - name: dotnet build
        run: dotnet build -c Release
      - name: dotnet run
        run: dotnet run --project ./src/CSharp/MathRunner/MathRunner.csproj -c Release
